// Public portfolio copy, adapted from the supplied research and industry CVs.
// Project results refer to the reported experiments, not general performance claims.
export const content = {
  en: {
    title: 'Kavya Malhotra | Data Science & Machine Learning',
    description: 'Kavya Malhotra - data science and machine learning at UCL. Research in tool-augmented AI, multilingual reasoning, and open-ended learning.',
    skip: 'Skip to content', navigation: 'Primary navigation', languageLabel: 'Language',
    openMenu: 'Open navigation menu', closeMenu: 'Close navigation menu',
    nav: ['Projects', 'Experience', 'Education', 'Skills', 'Contact'],
    hero: {
      eyebrow: 'Data Science · Machine Learning',
      intro: [
        'Hello and welcome to my portfolio! I am an MSc Data Science and Machine Learning student at University College London with experience in development and applied artificial intelligence.',
        'Experienced in a variety of programming languages, but mainly Python. Well-versed with other related topics such as Deep Learning, Applied ML, Natural Language Processing, and Retrieval Augmented Generation, with experience in large-scale AI systems at large companies.',
      ],
      location: 'From Bergen, Norway. Based in London.',
      projects: 'Explore my work', contact: 'Get in touch', print: 'Print this page',
      note: 'MSc Data Science & Machine Learning · UCL · Expected September 2026',
    },
    projects: {
      title: 'Selected work', intro: 'Three projects in how AI systems learn, reason, and use evidence.',
      more: 'More projects', less: 'Fewer projects', source: 'View code', enquiry: 'Ask about this research',
      contribution: 'The work', outcome: 'What we found', thesisOutcome: 'What I found',
      items: [
        { id: 'biomedical', title: 'Tool-augmented AI for biomedical research', kind: 'MSc dissertation · UCL · 2026',
          description: 'Three studies on literature screening, evidence synthesis, and grounded hypothesis formulation.',
          contribution: 'Designed workflows and evaluations spanning active learning, RAG, knowledge graphs, and agents, with checks for provenance, leakage, robustness, and computational cost.',
          outcome: 'Greater retrieval and agentic complexity did not show clear improvements. Evidence selection and provenance were key to reliability.',
          tags: ['RAG', 'LLM evaluation', 'Agentic AI'], status: 'Manuscript in preparation', diagram: ['Literature', 'Evidence', 'Evaluation'] },
        { id: 'mule', title: 'MuLE: Multilingual Language Equilibrium', kind: 'Group research project · UCL · 2026',
          description: 'Investigating DPO as a lower-cost alternative to GRPO for multilingual reasoning.',
          contribution: 'Developed a consensus-based preference-pair pipeline with dynamic pivot-language selection. Fine-tuned and evaluated a 1.5B-parameter model using QLoRA, Hugging Face, Unsloth, and Azure ML.',
          outcome: 'Performance improved on easy and medium tasks, while non-English language consistency declined on harder problems.',
          tags: ['DPO', 'QLoRA', 'Multilingual NLP'], diagram: ['EN', 'FR', 'PT', 'ES'] },
        { id: 'souping', title: 'Evolutionary methods for model souping', kind: 'Group research project · UCL · 2026',
          description: 'Treating the combination of model weights as an open-ended search problem.',
          contribution: 'Implemented MAP-Elites, SAIL, and CMA-ES to explore model-weight combinations, comparing them with uniform, greedy, SoCE, and learned-soup baselines.',
          outcome: 'Evolutionary soups matched or exceeded baseline methods in the experiments while producing more diverse weight combinations.',
          tags: ['MAP-Elites', 'CMA-ES', 'Open-ended learning'], diagram: ['Search', 'Combine', 'Evaluate'] },
      ],
      other: [
        { id: 'sequence', title: 'Sequence models for NLP', description: 'CBOW embeddings, multi-head attention, RNNs, GRUs, LSTMs, and beam search in PyTorch.' },
        { id: 'lanes', title: 'Lane detection', description: 'A computer vision model that highlights road lanes in video from a moving car.' },
        { id: 'detection', title: 'Object localisation & detection', description: 'Localising and detecting objects with convolutional neural networks.' },
        { id: 'trees', title: 'Decision trees & random forests', description: 'An ID3 decision tree implemented from scratch and extended into a random forest.' },
        { id: 'mnist', title: 'MNIST pipeline', description: 'Data analysis and model development for handwritten digit recognition.' },
        { id: 'gradient', title: 'Gradient descent', description: 'A manual implementation of gradient descent in PyTorch.' },
        { id: 'portfolio', title: 'This portfolio', description: 'A bilingual React portfolio with a focus on simplicity and accessibility.' },
      ],
    },
    experience: {
      title: 'Experience', intro: 'Applied AI, software development, and working with real-world data.',
      items: [
        { company: 'DNB', role: 'AI developer · Internship', date: 'Jun – Aug 2025', location: 'Oslo, Norway', bullets: ['Contributed to internal AI tooling, RAG chatbots, documentation systems, and cloud-based services.', 'Supported development and integration of AI workflows in a large-scale environment.'] },
        { company: 'Indisk Emporium AS', role: 'Developer', date: 'Jan 2021 – Jun 2025', location: 'Bergen, Norway', bullets: ['Maintained and extended web systems and product databases.', 'Supported data analysis for planning and operational improvements.'] },
        { company: 'Vogue International', role: 'Junior developer · Internship', date: '2024 – 2025', location: 'Remote · New Delhi, India', bullets: ['Assisted with export documentation and management software for operational workflows.'] },
        { company: 'Digiscreens', role: 'Developer · Internship', date: 'Aug – Dec 2023', location: 'Bergen, Norway', bullets: ['Built data-processing functions, tests, plots, and web interfaces for research on European streaming media.', 'Collaborated with a university project team and an external client.'] },
      ],
    },
    education: {
      title: 'Education',
      items: [
        { institution: 'University College London', location: 'London, UK', degree: 'MSc Data Science and Machine Learning', date: '2025 – 2026', status: 'Expected September 2026', description: 'Bayesian deep learning, reinforcement learning, machine vision, statistical NLP, and open-endedness and general intelligence.' },
        { institution: 'University of Bergen', location: 'Bergen, Norway', degree: 'BSc Data Science', date: '2021 – 2024', status: 'Completed', description: 'Machine learning, deep learning, algorithms, databases, software development, and the mathematical foundations of data science.' },
      ],
      note: 'References and transcripts available on request.',
    },
    skills: {
      title: 'Tools & interests',
      groups: [
        { title: 'AI & machine learning', text: 'PyTorch, JAX, Hugging Face, vLLM, NLP, deep learning, reinforcement learning, RAG, and LLM evaluation.' },
        { title: 'Programming & infrastructure', text: 'Python, Java, JavaScript, HTML, CSS, SQL, C, MATLAB, Git, Microsoft Azure, Linux, and Jupyter.' },
        { title: 'Research interests', text: 'Agentic AI, tool augmentation, world models, open-ended learning, and reliable evaluation.' },
      ],
      personalTitle: 'Hobbies',
      personal: 'Football, hiking, strength training, motorsport, gaming, and reading. I also enjoy astronomy and learning about the world through science.',
    },
    languages: { title: 'Languages', text: 'English, Norwegian, and Hindi/Urdu - native-level proficiency.' },
    certifications: { title: 'Continued learning', intro: 'Selected courses and certificates from Google and Codecademy.', show: 'View courses & certificates', provider: 'Course provider', certificate: 'View certificate' },
    footer: { title: 'Contact', top: 'Back to top' },
  },
  no: {
    title: 'Kavya Malhotra | Datavitenskap og maskinlæring',
    description: 'Kavya Malhotra - datavitenskap og maskinlæring ved UCL. Forskning på KI med verktøystøtte, flerspråklig resonnering og åpen læring.',
    skip: 'Hopp til innhold', navigation: 'Hovedmeny', languageLabel: 'Språk',
    openMenu: 'Åpne meny', closeMenu: 'Lukk meny',
    nav: ['Prosjekter', 'Erfaring', 'Utdanning', 'Ferdigheter', 'Kontakt'],
    hero: {
      eyebrow: 'Datavitenskap · Maskinlæring',
      intro: [
        'Hei og velkommen til porteføljen min! Jeg er masterstudent i datavitenskap og maskinlæring ved University College London, med erfaring innen programvareutvikling og anvendt kunstig intelligens.',
        'Jeg har erfaring med flere programmeringsspråk, først og fremst Python. Jeg er kjent med dyp læring, anvendt maskinlæring, natural language processing og retrieval-augmented generation (RAG), samt erfaring med KI-systemer i stor skala hos store firmaer.',
      ],
      location: 'Fra Bergen. Bosatt i London.',
      projects: 'Se prosjektene mine', contact: 'Ta kontakt', print: 'Skriv ut siden',
      note: 'Master i datavitenskap og maskinlæring · UCL · Forventet fullført september 2026',
    },
    projects: {
      title: 'Utvalgte prosjekter', intro: 'Tre prosjekter om hvordan KI-systemer lærer, resonnerer og bruker kunnskapsgrunnlag.',
      more: 'Flere prosjekter', less: 'Færre prosjekter', source: 'Se kode', enquiry: 'Spør om forskningen',
      contribution: 'Arbeidet', outcome: 'Hva vi fant', thesisOutcome: 'Hva jeg fant',
      items: [
        { id: 'biomedical', title: 'KI med verktøystøtte for biomedisinsk forskning', kind: 'Masteroppgave · UCL · 2026',
          description: 'Tre studier av screening, kunnskapssyntese og formulering av kildeforankrede hypoteser.',
          contribution: 'Utformet arbeidsflyter og evalueringer med aktiv læring, RAG, kunnskapsgrafer og agenter. Kontrollerte blant annet sporbarhet, datalekkasje, robusthet og kostnader.',
          outcome: 'Mer komplekse søke- og agentløsninger ga ingen tydelige gevinster. Utvalg av kilder og sporbarhet var avgjørende for påliteligheten.',
          tags: ['RAG', 'LLM-evaluering', 'KI-agenter'], status: 'Manuskript under utarbeidelse', diagram: ['Litteratur', 'Kilder', 'Evaluering'] },
        { id: 'mule', title: 'MuLE: Multilingual Language Equilibrium', kind: 'Forskningsprosjekt i gruppe · UCL · 2026',
          description: 'Undersøkte DPO som et rimeligere alternativ til GRPO for flerspråklig resonnering.',
          contribution: 'Utviklet en konsensusbasert prosess for preferansepar med dynamisk valg av referansespråk. Finetunet og evaluerte en modell med 1,5 milliarder parametere med QLoRA, Hugging Face, Unsloth og Azure ML.',
          outcome: 'Resultatene ble bedre på enkle og middels vanskelige oppgaver, mens modellen var mindre konsekvent i språkvalget på vanskeligere oppgaver på andre språk enn engelsk.',
          tags: ['DPO', 'QLoRA', 'Flerspråklig NLP'], diagram: ['EN', 'FR', 'PT', 'ES'] },
        { id: 'souping', title: 'Evolusjonære metoder for model souping', kind: 'Forskningsprosjekt i gruppe · UCL · 2026',
          description: 'Utforsket kombinasjon av modellvekter som et åpent søkeproblem.',
          contribution: 'Implementerte MAP-Elites, SAIL og CMA-ES for å utforske kombinasjoner av modellvekter. Sammenlignet med uniform, greedy, SoCE og learned-soup som referansemetoder.',
          outcome: 'De evolusjonære metodene oppnådde like gode eller bedre resultater enn referansemetodene i forsøkene, og ga mer varierte kombinasjoner av modellvekter.',
          tags: ['MAP-Elites', 'CMA-ES', 'Åpen læring'], diagram: ['Søk', 'Kombiner', 'Evaluer'] },
      ],
      other: [
        { id: 'sequence', title: 'Sekvensmodeller for NLP', description: 'CBOW, multi-head attention, RNN, GRU, LSTM og beam search implementert i PyTorch.' },
        { id: 'lanes', title: 'Deteksjon av kjørefelt', description: 'En modell for maskinsyn som markerer kjørefelt i video fra en bil i bevegelse.' },
        { id: 'detection', title: 'Lokalisering og deteksjon av objekter', description: 'Lokalisering og deteksjon av objekter med konvolusjonsnettverk.' },
        { id: 'trees', title: 'Beslutningstrær og random forests', description: 'Et ID3 decision tree implementert fra bunnen av og utvidet til en random forest.' },
        { id: 'mnist', title: 'MNIST', description: 'Dataanalyse og modellutvikling for gjenkjenning av håndskrevne sifre.' },
        { id: 'gradient', title: 'Gradient descent', description: 'En manuell implementering av gradient descent i PyTorch.' },
        { id: 'portfolio', title: 'Denne porteføljen', description: 'En tospråklig React-portefølje med vekt på enkelhet og tilgjengelighet.' },
      ],
    },
    experience: {
      title: 'Arbeidserfaring', intro: 'Anvendt KI, programvareutvikling og arbeid med data fra virkeligheten.',
      items: [
        { company: 'DNB', role: 'KI-utvikler · Praksis', date: 'Juni – august 2025', location: 'Oslo', bullets: ['Bidro til interne KI-verktøy, RAG-chatboter, dokumentasjonssystemer og skybaserte tjenester.', 'Støttet utvikling og integrasjon av KI-arbeidsflyter i et stort teknologimiljø.'] },
        { company: 'Indisk Emporium AS', role: 'Utvikler', date: 'Januar 2021 – juni 2025', location: 'Bergen', bullets: ['Vedlikeholdt og videreutviklet nettsystemer og produktdatabaser.', 'Bidro med dataanalyse til planlegging og forbedring av driften.'] },
        { company: 'Vogue International', role: 'Juniorutvikler · Praksis', date: '2024 – 2025', location: 'Remote · New Delhi, India', bullets: ['Bisto med eksportdokumentasjon og programvare for dokumenthåndtering i operative workflower.'] },
        { company: 'Digiscreens', role: 'Utvikler · Praksis', date: 'August – desember 2023', location: 'Bergen', bullets: ['Utviklet funksjoner for databehandling, tester, visualiseringer og nettgrensesnitt for forskning på europeiske strømmetjenester.', 'Samarbeidet med en prosjektgruppe ved universitetet og en ekstern klient.'] },
      ],
    },
    education: {
      title: 'Utdanning',
      items: [
        { institution: 'University College London', location: 'London, Storbritannia', degree: 'Master i datavitenskap og maskinlæring', date: '2025 – 2026', status: 'Forventet fullført september 2026', description: 'Bayesiansk dyp læring, forsterkende læring, maskinsyn, statistisk NLP, åpen læring og generell intelligens.' },
        { institution: 'Universitetet i Bergen', location: 'Bergen', degree: 'Bachelor i datavitenskap', date: '2021 – 2024', status: 'Fullført', description: 'Maskinlæring, dyp læring, algoritmer, databaser, systemutvikling og det matematiske grunnlaget for datavitenskap.' },
      ],
      note: 'Referanser og karakterutskrifter er tilgjengelige på forespørsel.',
    },
    skills: {
      title: 'Ferdigheter og interesser',
      groups: [
        { title: 'KI og maskinlæring', text: 'PyTorch, JAX, Hugging Face, vLLM, NLP, dyp læring, forsterkningslæring, RAG og evaluering av språkmodeller.' },
        { title: 'Programmering og infrastruktur', text: 'Python, Java, JavaScript, HTML, CSS, SQL, C, MATLAB, Git, Microsoft Azure, Linux og Jupyter.' },
        { title: 'Forskningsinteresser', text: 'KI-agenter, verktøystøtte, verdensmodeller, åpen læring og pålitelig evaluering.' },
      ],
      personalTitle: 'Hobbyer',
      personal: 'Fotball, fjellturer, trening, motorsport, dataspill og lesing. Jeg er også interessert i astronomi og i å forstå verden gjennom vitenskap.',
    },
    languages: { title: 'Språk', text: 'Engelsk, norsk og hindi/urdu - på morsmålsnivå.' },
    certifications: { title: 'Videre læring', intro: 'Utvalgte kurs og sertifikater fra Google og Codecademy.', show: 'Se kurs og sertifikater', provider: 'Kurstilbyder', certificate: 'Se sertifikat' },
    footer: { title: 'Kontakt', top: 'Til toppen' },
  },
};

export const projectUrls = {
  mule: 'https://github.com/Rauljo/MuLE',
  souping: 'https://github.com/kavmal7/COMP0258-project',
  sequence: 'https://github.com/kavmal7/Sequence-models',
  lanes: 'https://github.com/kavmal7/Lane-detection',
  detection: 'https://github.com/kavmal7/object-detection',
  trees: 'https://github.com/kavmal7/decision-tree',
  mnist: 'https://github.com/kavmal7/MNIST-model',
  gradient: 'https://github.com/kavmal7/grad_descent',
  portfolio: 'https://github.com/kavmal7/Online-CV',
};
